SELECT p.ID_PRODUTO, p.TITULO
FROM PRODUTO p;

SELECT *
FROM PRODUTO;

SELECT * FROM
             ITEM_USUARIO;

SELECT *
FROM ACHIEVEMENT a
ORDER BY a.ID_ACHIEVEMENT;

SELECT *
FROM EQUIPE;

SELECT *
FROM ITEM i
         JOIN PRODUTO p ON i.ID_PRODUTO = p.ID_PRODUTO;

SELECT *
FROM CATEGORIA;

SELECT *
FROM CATEGORIA_PRODUTO;

SELECT *
FROM PRODUTO_USUARIO pu
         JOIN PRODUTO p ON pu.ID_PRODUTO = p.ID_PRODUTO
WHERE pu.ID_USUARIO = 13;

SELECT *
FROM ACHIEVEMENT_USUARIO;

SELECT *
FROM USUARIO
WHERE ID_USUARIO >= 10
ORDER BY ID_USUARIO;

SELECT *
FROM FUNCIONARIO;



SELECT *
FROM USUARIO u
         JOIN DESENVOLVEDOR d ON u.ID_USUARIO = d.ID_USUARIO;

SELECT *
FROM ACHIEVEMENT_USUARIO;

SELECT *
FROM CHAMADO_SUPORTE;

SELECT *
FROM ITEM_USUARIO;

-- Todos os produtos em ordem decrescente por preço
SELECT *
FROM PRODUTO p
ORDER BY p.PRECO desc;

-- Itens associados aos seus devidos jogos
SELECT p.ID_PRODUTO, p.TITULO, p.PRECO, i.nome, i.PRECO
FROM PRODUTO p
         JOIN ITEM i ON i.ID_PRODUTO = p.ID_PRODUTO;

-- Quantidade de Achievements de um usuario
SELECT u.NOME, COUNT(*) AS qtd_achievement
FROM ACHIEVEMENT_USUARIO au
         JOIN USUARIO u ON au.ID_USUARIO = u.ID_USUARIO
WHERE au.ID_USUARIO = 10
GROUP BY u.NOME;

-- Média de preço dos produtos
SELECT AVG(p.PRECO) AS MEDIA_PRECO
FROM PRODUTO p;

-- Jogos por desenvolvedor
SELECT p.ID_PRODUTO, p.TITULO, p.DATA_LANCAMENTO, d.ID_USUARIO, u.NOME, d.CNPJ, d.WEBSITE
FROM EQUIPE e
         JOIN DESENVOLVEDOR d ON e.ID_USUARIO = d.ID_USUARIO
         JOIN USUARIO u ON d.ID_USUARIO = u.ID_USUARIO
         JOIN PRODUTO p ON e.ID_PRODUTO = p.ID_PRODUTO;

-- Produtos com valor entre 10 e 50
SELECT *
FROM PRODUTO p
WHERE p.PRECO BETWEEN 10 AND 50;

-- Itens para cada usuario
SELECT u.ID_USUARIO, u.NOME, i.ID_ITEM, i.NOME
FROM ITEM_USUARIO iu
         JOIN USUARIO u ON iu.ID_USUARIO = u.ID_USUARIO
         JOIN ITEM i ON iu.ID_ITEM = i.ID_ITEM
ORDER BY u.ID_USUARIO;

-- Subquery com agregação
SELECT *
FROM PRODUTO p
WHERE p.PRECO > (SELECT AVG(prod.PRECO) FROM PRODUTO prod)
ORDER BY p.PRECO DESC;

-- View achievements por usuario
CREATE VIEW achievementsperuser AS
SELECT u.ID_USUARIO,
       u.NOME AS USERNAME,
       p.ID_PRODUTO,
       p.TITULO,
       a.ID_ACHIEVEMENT,
       a.NOME AS ACHIEVEMENT,
       a.DESCRICAO
FROM ACHIEVEMENT_USUARIO au
         JOIN ACHIEVEMENT a ON a.ID_ACHIEVEMENT = au.ID_ACHIEVEMENT
         JOIN USUARIO u ON au.ID_USUARIO = u.ID_USUARIO
         JOIN PRODUTO p ON a.ID_PRODUTO = p.ID_PRODUTO
ORDER BY u.ID_USUARIO;

select *
from achievementsperuser;

-- Coisas que podem ser adquiridas na plataforma
SELECT p.ID_PRODUTO AS ID, p.TITULO AS NOME, 'Produto' AS ORIGEM
FROM PRODUTO p
UNION
SELECT i.ID_ITEM, i.NOME, 'Item' AS ORIGEM
FROM ITEM i
UNION
SELECT a.ID_ACHIEVEMENT, a.NOME, 'Achievement' AS ORIGEM
FROM ACHIEVEMENT a
ORDER BY ORIGEM;

-- SELECTS PARA CHAMADOS_SUPORTE
SELECT *
FROM CHAMADO_SUPORTE cs
         JOIN FUNCIONARIO f ON f.ID_FUNCIONARIO = cs.ID_FUNCIONARIO
ORDER BY f.ID_FUNCIONARIO;

SELECT *
FROM CHAMADO_SUPORTE cs
         JOIN USUARIO u ON u.ID_USUARIO = cs.ID_USUARIO
ORDER BY u.ID_USUARIO;
